apiVersion: v1
kind: Service
metadata:
  name: grafana-srv
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - protocol: TCP
      port: 80         # порт для Ingress
      targetPort: 3000 # порт Grafana внутри пода
