---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  namespace: default
  labels:
    app: "diplom"
    component: web
spec:
  selector:
    app: "diplom"
    component: web
  ports:
    - port: 80
      name: lb-port
      targetPort: 80
  type: LoadBalancer
